name: "Automerge"
on:
  pull_request_target:
    branches:
      - main
      - 'release/*'
    paths:
      - 'services/**/*'
  workflow_dispatch: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on automated chart bump PRs
        uses: reitermarkus/automerge@v2
        if: startsWith(github.head_ref, 'chartbump/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-commit-title: ${pull_request.title}
          do-not-merge-labels: do-not-merge,do-not-merge/testing
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
